### ISSUE TITLE
Error: cannot open source file "openssl/opensslconf.h"

### ISSUE THREAD

**Issue by flleeppyy** [Lyut/SpotiHook#3]
I've been hunting around trying to figure out where this opensslconf.h file is and its not in any openssl builds, and I probably have to generate it myself, but I also cant find anything on building the file.
I've made sure to add the include folder in the properties.

Im using Visual Studio 2019

**Comment by flleeppyy** [comment]
also THERE ARE A FUCK TON OF ERRORS
HOW DID YOU EVEN MANAGE TO RUN THIS?!
![image](https://user-images.githubusercontent.com/18307183/84776890-c054eb00-af95-11ea-9300-5ac3a82d080f.png)

**Comment by flleeppyy** [comment]
Aight got it working
im extremely dumb lmfao

**Comment by flleeppyy** [comment]
fuck

**Comment by Lyut** [comment]
u ok?

**Comment by ShiniXi** [comment]
you crazy.

**Comment by flleeppyy** [comment]
yes I'm fine
