### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by Varidian** [Lyut/SpotiHook#4]
I built the files, do I drag and drop them into the Spotify folder like xspotify? Or is there a different installation method?

**Comment by Varidian** [comment]
Edit: Figured out you have to manually inject the DLL. Did so, the command prompt comes up and says everything is running, but I can't see the GUI in the Spotify window

**Comment by Lyut** [comment]
> 
> 
> Edit: Figured out you have to manually inject the DLL. Did so, the command prompt comes up and says everything is running, but I can't see the GUI in the Spotify window

press insert?

**Comment by Varidian** [comment]
Insert opens the window, but it's missing the download button and Now Playing text
![image](https://user-images.githubusercontent.com/14263991/90825992-95b54480-e2ee-11ea-813f-6ced0a1693ee.png)

**Comment by Varidian** [comment]
I've tried downgrading, but for some reason every single installer for old versions just installs the latest version of Spotify. Seems like changing all the memory addresses is my only option, so I'ma go try and learn how to do that.
