### ISSUE TITLE
HOW DOES IT WORK?

### ISSUE THREAD

**Issue by pippocampa** [Lyut/SpotiHook#6]
Sorry for bad grammar,
i am not good with these things, could you make a file where you explain well how to start the file and download the song please? sorry if it's not a "issue" but I didn't know how to contact you

**Comment by Lyut** [comment]
Ciao,
purtroppo in questo periodo sono un po' occupato con degli altri progetti privati, probabilmente in seguito proverò ad aggiornare il programma e in caso a semplificarne l'utilizzo, magari aggiungendo i file compilati.

Ora come ora spotify ha aggiornato gli algoritmi e il programma non funge più

Buon proseguimento
